apiVersion: v1
kind: Service
metadata:
  name: kiali-external
  namespace: kiali-operator
spec:
  ports:
  - port: 20001
    targetPort: 20001
    name: http-kiali
  selector:
    app: kiali
  type: LoadBalancer